# Generated by Django 5.0.6 on 2026-09-24 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('disaster_type', models.CharField(choices=[('flood', 'Flood'), ('fire', 'Fire'), ('landslide', 'Landslide'), ('earthquake', 'Earthquake'), ('storm', 'Storm'), ('building_collapse', 'Building Collapse'), ('road_accident', 'Road Accident'), ('other', 'Other Emergency')], max_length=30)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=160)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Responder Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('is_public', models.BooleanField(default=True, help_text='Show on the public alerts page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'drers_report',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('citizen', 'Citizen'), ('responder', 'Emergency Responder'), ('admin', 'Administrator')], default='citizen', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'drers_profile',
            },
        ),
        migrations.CreateModel(
            name='ResponseUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('new_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('assigned', 'Responder Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='core.disasterreport')),
            ],
            options={
                'db_table': 'drers_response_update',
                'ordering': ['-created_at'],
            },
        ),
    ]
