# Generated by Django 5.0.6 on 2026-09-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disasterreport',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disasterreport',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
