# Generated by Django 5.0.6 on 2026-10-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='is_red',
            new_name='is_read',
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
